### ISSUE TITLE
Unable to Use the Salesforce Test Tenant

### ISSUE THREAD

**Issue by fbertilsson** [kdcllc/CometD.NetCore.Salesforce#10]
I would like to be able to use the Salesforce test tenant with this library.

When using the following configuration:
    `"LoginUrl": "https://test.salesforce.com",`
you get an error when the token refresh method is called inside the library. This is because the configured LoginUrl is not used when making the call:
```
await authClient.TokenRefreshAsync(
                           options.RefreshToken,
                           options.ClientId)
```
This is fixed in PR #9

**Comment by kdcllc** [comment]
@fbertilsson this is correct. I realized that I never merged dev branch to master with this fix https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/149af4ad72cfb1f04754fbfcd6e61e20a5b0e8da/src/CometD.NetCore.Salesforce/StreamingClientExtensions.cs#L70

**Comment by kdcllc** [comment]
@fbertilsson,

Thanks for opening the issue. I pushed my changes to a new branch and released this preview nuget package. Can you please test it with your app?

Add this to your nuget feed: https://www.myget.org/F/kdcllc/api/v3/index.json

```bash
  dotnet add package CometD.NetCore.Salesforce --version 2.2.0-preview
```

Thanks,

**Comment by kdcllc** [comment]
@fbertilsson Please install the latest from nuget package it should fix the bug. I will keep this issue open until you confirm it. Thanks!

**Comment by fbertilsson** [comment]
I can confirm that I now can declare a LoginUrl  of ```"https://test.salesforce.com"``` in my program and get a connection to Salesforce Event Hub, using package version 2.2.1. Sorry for the delay.
Thanks for fixing it quickly.
