### ISSUE TITLE
Replaying historical events?

### ISSUE THREAD

**Issue by johnny-chan** [kdcllc/CometD.NetCore.Salesforce#8]
Hi, 

Does this support replaying historical push topic notifications? 

When our service starts up, I've subscribed to an existing push topic "/topic/SomeTopicName" (i've used an example here)  using the following code

IClientSessionChannel channel = _bayeuxClient.GetChannel("/topic/SomeTopicName", 102);
channel?.Subscribe(listener);

When the application starts up, i was expecting our subscribers to pickup historic notifications starting with replayId of 102 for the "/topic/SomeTopicName" - this was not happening. it was only picking up new events.

**Comment by kdcllc** [comment]
@johnny-chan, I believe Salesforce keeps 24 hours of the reply id. Does your test fall into that window?

**Comment by johnny-chan** [comment]
yeah, it did fall into the 24 hr window. I'm not using the ResillientStreamClient, but establishing connection with the BayeuxClient directly.  i looked at the resillientStreamingClient code and found out how to add the replay extension. This was what i was missing. 

_replayIdExtension = new ReplayExtension();
_bayeuxClient.AddExtension(_replayIdExtension);

**Comment by JayXT** [comment]
Hi Guys,
Is there anything else apart from adding the ReplayExtension needed to make BayuexClient listen to messages starting after the supplied replayId? I've tried adding ReplayExtension, but to no avail.
Thank you.

**Comment by kdcllc** [comment]
@JayXT please see this class https://github.com/kdcllc/CometD.NetCore.Salesforce/blob/81db2fa8e2fe7b8b6365cd40410895fe61c1088f/src/CometD.NetCore.Salesforce/ResilientStreamingClient.cs#L203

**Comment by JayXT** [comment]
@kdcllc, thank you for your help. Somehow everything just started to work just with the ReplayExtension I've added before. However, I'll let you know if there are any other related issues.
